import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"
import Image from "next/image"
import Login from "../components/Login";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gradient-to-r from-orange-500 via-rose-400 to-orange-400 w-full h-20 flex justify-between items-center p-4 bg-orange-500">
          <Link href="/" className="justify-start ml-32">
            <Image
              src="/unibui_logo.png"
              alt="Unibui Logo"
              width={237}
              height={77} 
              className="w-40 h-auto"
            />
          </Link>
          <div className="flex space-x-12 pr-14">
            <Link href="/start" className="text-xl font-bold">Get Started</Link>
            <Link href="/jobs" className="text-xl font-bold">Jobs Near You</Link>
            <Link href="/deals" className="text-xl font-bold">Rewards</Link>
            <Login></Login>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
